recipes/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from . import views

app_name = 'recipes'

urlpatterns = [
    path('', views.home, name='home'),
    path('recipes/category/<int:category_id>/', views.category, name='category'),
    path('recipes/<int:id>/', views.recipes, name='detail'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

recipesRoot/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('recipes.urls'))   # /
]

recipes/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Recipe(models.Model):
    title = models.CharField(max_length=65)
    description = models.CharField(max_length=165)
    slug = models.SlugField()
    preparation_time = models.IntegerField()
    preparation_time_unit = models.CharField(max_length=65)
    servings = models.IntegerField()
    servings_unit = models.CharField(max_length=65)
    preparation_steps = models.TextField()
    preparation_steps_is_html = models.BooleanField(default=False)
    created_at = models.DateField(auto_now_add=True)
    updated_at = models.DateField(auto_now=True)
    is_published = models.BooleanField(default=False)
    cover = models.ImageField(upload_to='recipes/covers/%Y/%m/%d/')

    category = models.ForeignKey(
        Category, 
        on_delete=models.SET_NULL,
        null=True, 
        blank=True, 
        default=None
    ) # when delete, set null to camp


    author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return self.title

recipes/views.py
# from utils.recipes.factory import make_recipe
from django.shortcuts import get_list_or_404, render

from .models import Recipe


# Create your views here.
def home(request):
    recipes = Recipe.objects.filter(is_published=True).order_by('-id')  #Recipe.objects.all()

    return render(request, 'recipes/pages/home.html', context= {
        'recipes': recipes
    })

def category(request, category_id):
    # # filter objects by category // category__id = foreign key
    # recipes = Recipe.objects.filter(
    #     category__id=category_id,
    #     is_published=True
    # )
    # if not recipes:
    #     raise Http404('Not Found =(')

    recipes = get_list_or_404(
        Recipe.objects.filter(
            category__id=category_id,
            is_published=True
        ).order_by('-id')
    )

    return render(request, 'recipes/pages/category.html', context= {
        'recipes': recipes,
        'title': f'{recipes[0].category.name} - Category | '
    })

def recipes(request, id):
    # recipe = Recipe.objects.get(id=id)
    recipe = Recipe.objects.filter(
        id=id,
        is_published=True
    ).order_by('-id').first()
    
    return render(request, 'recipes/pages/recipes-view.html', context={
        'recipe': recipe,
        'is_detail_page': True,
    })

recipes/templates/recipes/pages/category.html
{% extends 'global/home.html' %}

{% block title %} {{ title }} {% endblock title %}

{% block content %}
<div class="main-content main-content-list container">
  {% for recipe in recipes %}
    {% include "recipes/partials/recipes.html" %}
  {% endfor %}
</div>
{% endblock content %}

recipes/templates/recipes/pages/home.html
{% extends 'global/home.html' %}

{% block title %} Home | {% endblock title %}

{% block content %}
<div class="main-content main-content-list container">
  {% for recipe in recipes %}
    {% include "recipes/partials/recipes.html" %}
  {% endfor %}
</div>
{% endblock content %}

recipes/templates/recipes/pages/recipes-view.html
{% extends 'global/home.html' %}

{% block title %} Recipe Detail | {% endblock title %}

{% block content %}
<div class="main-content main-content-detail container">
  {% include "recipes/partials/recipes.html" %}
</div>
{% endblock content %}

recipes/templates/recipes/partials/footer.html
<footer class="main-footer">
  <div class="developer">
    <a href="https://www.linkedin.com/in/edypnog/" target="_blank" rel="noreferrer noopener">Projected by Edy Nogueira</a>
  </div>

  <i class="fa fa-heart" aria-hidden="true"></i>

  <div class="powered">
    <a href="https://www.djangoproject.com/" target="_blank" rel="noreferrer noopener">Powered by Django</a>
  </div>

  <p>
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Inventore voluptates, aperiam debitis numquam, tempora corrupti minima commodi velit fuga libero beatae sapiente nisi, deleniti soluta.
  </p>
</footer>

recipes/templates/recipes/partials/head.html
{% load static %}
<meta charset="UTF-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">

{% comment %} font awesome links {% endcomment %}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/fontawesome.min.css"
  integrity="sha512-P9vJUXK+LyvAzj8otTOKzdfF1F3UYVl13+F8Fof8/2QNb8Twd6Vb+VD52I7+87tex9UXxnzPgWA3rH96RExA7A=="
  crossorigin="anonymous" referrerpolicy="no-referrer" />
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/solid.min.css"
  integrity="sha512-tk4nGrLxft4l30r9ETuejLU0a3d7LwMzj0eXjzc16JQj+5U1IeVoCuGLObRDc3+eQMUcEQY1RIDPGvuA7SNQ2w=="
  crossorigin="anonymous" referrerpolicy="no-referrer" />
<script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/js/brands.min.js"
  integrity="sha512-8Jp5PI7qKEn304XONokQQRgiu/1P9kTBlvpLc7zRukkTBYGKt6z4CkwJUJhCwwWYnjSdxJcGqW9ifT7ZxPNgbg=="
  crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

{% comment %} styles {% endcomment %}
<link rel="stylesheet" href="style.css">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Raleway:wght@300;500;600;700&display=swap" rel="stylesheet">

<link rel="stylesheet" href="{% static 'recipes/css/styles.css' %}">

recipes/templates/recipes/partials/header.html
<header class="main-header-container">
  <div class="main-header container">
    <h1>
      <a class="main-logo" href="{% url 'recipes:home' %}">
        <i class="fas fa-utensils main-logo-icon" aria-hidden="true"></i>
        <span class="main-logo-text">Recipes Book</span>
      </a>
    </h1>
  </div>
</header>

recipes/templates/recipes/partials/recipes.html
<div class="recipe recipe-list-item">
  <div class="recipe-cover">
    <a href="{% url 'recipes:detail' recipe.id %}">
      <img src="{{ recipe.cover.url }}" alt="">
    </a>
  </div>
  <div class="recipe-title-container">
    <h2 class="recipe-title">
      <a href="{% url 'recipes:detail' recipe.id %}">
        {{ recipe.title }}
      </a>
    </h2>
  </div>

  <div class="recipe-author">

    {% if recipe.author is not None %}
      <span class="recipe-author-item">
        <i class="fas fa-user"></i>
        {% if recipe.author.first_name %}
          {{ recipe.author.first_name }}
          {{ recipe.author.last_name }}
        {% else %}
          {{ recipe.author.username }}
        {% endif %}
      </span>
    {% endif %}

    <span class="recipe-author-item">
      <i class="fas fa-calendar-alt"></i>
      {{ recipe.created_at|date:'d/m/Y' }}
    </span>

    {% if recipe.category is not None %}
      <span class="recipe-author-item">
        <a href="{% url 'recipes:category' recipe.category.id %}">
          <i class="fas fa-layer-group"></i>
          <span>{{ recipe.category.name|upper }}</span>
        </a>
      </span>
    {% endif %}

  </div>

  <div class="recipe-content">
    <p>
      {{ recipe.description }}
    </p>
  </div>

  <div class="recipe-meta-container">
    <div class="recipe-meta recipe-preparation">
      <h3 class="recipe-meta-title"><i class="fas fa-stopwatch"></i> Tutorial</h3>
      <div class="recipe-meta-text">
        {{ recipe.preparation_time }} {{ recipe.preparation_time_unit }}
      </div>
    </div>
    <div class="recipe-meta recipe-servings">
      <h3 class="recipe-meta-title"><i class="fas fa-pizza-slice"></i> Pieces</h3>
      <div class="recipe-meta-text">
        {{ recipe.servings }} {{ recipe.servings_unit }}
      </div>
    </div>
  </div>

  {% if is_detail_page is not True %}
  <footer class="recipe-footer">
    <a class="recipe-read-more button button-dark button-full-width" href="{% url 'recipes:detail' recipe.id %}">
      <i class="fas fa-eye"></i>
      <span class="ml-1">Read More...</span>
    </a>
  </footer>
  {% endif %}

  {% if is_detail_page is True %}
    
    <div class="recipe-content">
      {% if recipe.preparation_steps_is_html is True %}
        <p>
          {{ recipe.preparation_steps|safe }}
        </p>
      {% else %}
        <p>
          {{ recipe.preparation_steps|linebreaksbr }}
        </p>
      {% endif %}
    </div>
  
  {% endif %}

</div>

recipes/templates/recipes/partials/search.html
<div class="search-container">
  <div class="container">
    <form action="" class="search-form">
      <input type="search" name="search" class="search-input" />
      <button type="submit" class="search-btn">
        <i class="fa fa-search" aria-hidden="true"></i>
      </button>
    </form>
  </div>
</div>